language: cpp

os:
  - osx

addons:
  homebrew:
    packages:
    - sdl2_mixer
    - sdl2_ttf
    - libsodium
    
install:
  - brew upgrade cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(sysctl -n hw.physicalcpu)
