language: cpp

os:
  - osx
  
addons:
  homebrew:
    update: true
    packages:
    - sdl2_mixer
    - sdl2_ttf
    - libsodium

script:
     - mkdir build
     - cd build
     - cmake ..
     - make -j$(sysctl -n hw.physicalcpu)
