version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y g++ cmake libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev libsodium-dev
      - run: mkdir build32
      - run: cd build && cmake ..
      - run: cd build && make -j$(nproc)
      - store_artifacts: {path: ./build/devilutionx, destination: devilutionx_linux_x64}
