version: 2
jobs:
  diablo_109b:
    docker:
      - image: diasurgical/riivaaja:stable
    steps:
      - checkout
      - run: make -f MakefileVC
  linux:
    docker:
      - image: debian:stretch-backports
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y mingw-w64
      - run: make
      - run: make debug

workflows:
  version: 2
  testflow:
    jobs:
      - diablo_109b
      - linux
