version: 2
jobs:
  diablo_109b:
    docker:
      - image: diasurgical/riivaaja:stable
    steps:
      - checkout
      - run: make -f MakefileVC
  diablo_109b_diff:
    machine: true
    steps:
      - checkout
      - run: |
          set -e
          wget https://github.com/diasurgical/devilution-comparer/releases/download/v0.4.0/devilution-comparer-v0.4.0-x86_64-unknown-linux-gnu.tar.xz
          tar xf devilution-comparer-v0.4.0-x86_64-unknown-linux-gnu.tar.xz
          mv comparer-config/diablo.toml comparer-config.toml
          echo '#!/bin/sh' | sudo tee /bin/wine
          echo 'docker run -v $(pwd):/root/devilution --entrypoint "/usr/bin/wine" diasurgical/riivaaja:stable $(basename $1) $2 $3' | sudo tee --append /bin/wine
          sudo chmod +x /bin/wine
          docker run -v $(pwd):/root/devilution -e MAKE_BUILD=pdb diasurgical/riivaaja:stable
          ./devilution-comparer generate-full Diablo.exe --no-mem-disp --truncate-to-original
          docker run -v $(pwd):/root/devilution diasurgical/riivaaja:stable ../status.sh
          .travis/are-we-d1-yet.sh "$(< accuracy.txt)" $DISCORD_WEBHOOK "Diablo 1.09b"
  linux:
    docker:
      - image: debian:stretch-backports
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y mingw-w64 make
      - run: make
      - run: make debug

workflows:
  version: 2
  testflow:
    jobs:
      - diablo_109b
      - diablo_109b_diff
      - linux
